/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author JamesGomez
 */
public class NewJFrame extends javax.swing.JFrame {

    public float primerNumero;
    public float segundoNumero;
    public String operador;
    
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        numero2 = new javax.swing.JButton();
        numero1 = new javax.swing.JButton();
        signoDividir = new javax.swing.JButton();
        numero3 = new javax.swing.JButton();
        numero4 = new javax.swing.JButton();
        numero5 = new javax.swing.JButton();
        numero6 = new javax.swing.JButton();
        signoMultiplicar = new javax.swing.JButton();
        numero7 = new javax.swing.JButton();
        numero8 = new javax.swing.JButton();
        numero9 = new javax.swing.JButton();
        signoMenos = new javax.swing.JButton();
        numero0 = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        signoMas = new javax.swing.JButton();
        eliminador = new javax.swing.JButton();
        porcentaje = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        vistaResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        numero2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        numero2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/numero-2.png"))); // NOI18N
        numero2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        numero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero2ActionPerformed(evt);
            }
        });

        numero1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        numero1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/redondo.png"))); // NOI18N
        numero1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero1ActionPerformed(evt);
            }
        });

        signoDividir.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        signoDividir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/division.png"))); // NOI18N
        signoDividir.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        signoDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoDividirActionPerformed(evt);
            }
        });

        numero3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        numero3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/numero-3.png"))); // NOI18N
        numero3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        numero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero3ActionPerformed(evt);
            }
        });

        numero4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        numero4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/numero-cuatro.png"))); // NOI18N
        numero4.setToolTipText("");
        numero4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        numero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero4ActionPerformed(evt);
            }
        });

        numero5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        numero5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/numero-5.png"))); // NOI18N
        numero5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        numero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero5ActionPerformed(evt);
            }
        });

        numero6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        numero6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/seis.png"))); // NOI18N
        numero6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        numero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero6ActionPerformed(evt);
            }
        });

        signoMultiplicar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        signoMultiplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/signo-de-multiplicacion.png"))); // NOI18N
        signoMultiplicar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        signoMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoMultiplicarActionPerformed(evt);
            }
        });

        numero7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        numero7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/siete.png"))); // NOI18N
        numero7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        numero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero7ActionPerformed(evt);
            }
        });

        numero8.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        numero8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/numero-8.png"))); // NOI18N
        numero8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        numero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero8ActionPerformed(evt);
            }
        });

        numero9.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        numero9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/numero-9.png"))); // NOI18N
        numero9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        numero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero9ActionPerformed(evt);
            }
        });

        signoMenos.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        signoMenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/boton-menos.png"))); // NOI18N
        signoMenos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        signoMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoMenosActionPerformed(evt);
            }
        });

        numero0.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        numero0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/cero.png"))); // NOI18N
        numero0.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        numero0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero0ActionPerformed(evt);
            }
        });

        punto.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        punto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/circulo.png"))); // NOI18N
        punto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });

        igual.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        igual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/signo-de-igual.png"))); // NOI18N
        igual.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        signoMas.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        signoMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/mas.png"))); // NOI18N
        signoMas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        signoMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoMasActionPerformed(evt);
            }
        });

        eliminador.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        eliminador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/AC_Mesa de trabajo 1.png"))); // NOI18N
        eliminador.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        eliminador.setOpaque(true);
        eliminador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminadorActionPerformed(evt);
            }
        });

        porcentaje.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        porcentaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/porcentaje.png"))); // NOI18N
        porcentaje.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentajeActionPerformed(evt);
            }
        });

        eliminar.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/borrar (3).png"))); // NOI18N
        eliminar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        vistaResultado.setBackground(new java.awt.Color(255, 255, 255));
        vistaResultado.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        vistaResultado.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        vistaResultado.setToolTipText("");
        vistaResultado.setAlignmentX(0.5F);
        vistaResultado.setOpaque(true);
        vistaResultado.setPreferredSize(new java.awt.Dimension(17, 18));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(eliminador, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(numero3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(signoDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(numero4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(numero5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(numero6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(signoMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(numero7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(numero8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(numero9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(signoMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(numero0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(signoMas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(vistaResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(vistaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminador, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signoDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signoMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signoMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signoMas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero1ActionPerformed
        this.vistaResultado.setText(this.vistaResultado.getText()+"1");
        
    }//GEN-LAST:event_numero1ActionPerformed

    private void signoDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoDividirActionPerformed
        this.primerNumero=Float.parseFloat(this.vistaResultado.getText());
        this.operador= "/";
        this.vistaResultado.setText("");
    }//GEN-LAST:event_signoDividirActionPerformed

    private void numero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero3ActionPerformed
        this.vistaResultado.setText(this.vistaResultado.getText()+"3");
    }//GEN-LAST:event_numero3ActionPerformed

    private void numero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero2ActionPerformed
        this.vistaResultado.setText(this.vistaResultado.getText()+"2");
    }//GEN-LAST:event_numero2ActionPerformed

    private void numero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero4ActionPerformed
        this.vistaResultado.setText(this.vistaResultado.getText()+"4");
    }//GEN-LAST:event_numero4ActionPerformed

    private void numero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero5ActionPerformed
        this.vistaResultado.setText(this.vistaResultado.getText()+"5");
    }//GEN-LAST:event_numero5ActionPerformed

    private void numero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero6ActionPerformed
        this.vistaResultado.setText(this.vistaResultado.getText()+"6");
    }//GEN-LAST:event_numero6ActionPerformed

    private void signoMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoMultiplicarActionPerformed
        this.primerNumero=Float.parseFloat(this.vistaResultado.getText());
        this.operador= "*";
        this.vistaResultado.setText("");
    }//GEN-LAST:event_signoMultiplicarActionPerformed

    private void numero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero7ActionPerformed
        this.vistaResultado.setText(this.vistaResultado.getText()+"7");
    }//GEN-LAST:event_numero7ActionPerformed

    private void numero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero8ActionPerformed
       this.vistaResultado.setText(this.vistaResultado.getText()+"8");
    }//GEN-LAST:event_numero8ActionPerformed

    private void numero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero9ActionPerformed
        this.vistaResultado.setText(this.vistaResultado.getText()+"9");
    }//GEN-LAST:event_numero9ActionPerformed

    private void signoMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoMenosActionPerformed
        this.primerNumero=Float.parseFloat(this.vistaResultado.getText());
        this.operador= "-";
        this.vistaResultado.setText("");
    }//GEN-LAST:event_signoMenosActionPerformed

    private void numero0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero0ActionPerformed
        this.vistaResultado.setText(this.vistaResultado.getText()+"0");
    }//GEN-LAST:event_numero0ActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        if(!(this.vistaResultado.getText().contains("."))){
           this.vistaResultado.setText(this.vistaResultado.getText()+".");
        
        }
    }//GEN-LAST:event_puntoActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        this.segundoNumero=Float.parseFloat(this.vistaResultado.getText());    
        switch(operador){
            case "+" : this.vistaResultado.setText(sincero(primerNumero+segundoNumero));
                break;
            case "-": this.vistaResultado.setText(sincero(primerNumero-segundoNumero));
                break;
            case "*": this.vistaResultado.setText(sincero(primerNumero*segundoNumero));    
                break;
            case "/": this.vistaResultado.setText(sincero(primerNumero/segundoNumero));   
                break;
        }
        
    }//GEN-LAST:event_igualActionPerformed

    private void signoMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoMasActionPerformed
        this.primerNumero=Float.parseFloat(this.vistaResultado.getText());
        this.operador= "+";
        this.vistaResultado.setText("");
    }//GEN-LAST:event_signoMasActionPerformed

    private void eliminadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminadorActionPerformed
       this.vistaResultado.setText("");
    }//GEN-LAST:event_eliminadorActionPerformed

    private void porcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_porcentajeActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        String textoActual = this.vistaResultado.getText();
        String nuevoTexto = textoActual.substring(0, textoActual.length()- 1);
        this.vistaResultado.setText(nuevoTexto);
    }//GEN-LAST:event_eliminarActionPerformed

    public String sincero(float resultado){
        String retorno=("");
        retorno = Float.toString(resultado);
        if(resultado%1==0){
            retorno = retorno.substring(0,retorno.length()-2);
        
        }
        return retorno;        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminador;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton igual;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton numero0;
    private javax.swing.JButton numero1;
    private javax.swing.JButton numero2;
    private javax.swing.JButton numero3;
    private javax.swing.JButton numero4;
    private javax.swing.JButton numero5;
    private javax.swing.JButton numero6;
    private javax.swing.JButton numero7;
    private javax.swing.JButton numero8;
    private javax.swing.JButton numero9;
    private javax.swing.JButton porcentaje;
    private javax.swing.JButton punto;
    private javax.swing.JButton signoDividir;
    private javax.swing.JButton signoMas;
    private javax.swing.JButton signoMenos;
    private javax.swing.JButton signoMultiplicar;
    private javax.swing.JLabel vistaResultado;
    // End of variables declaration//GEN-END:variables
}
